# Site settings
title: Matthew D. Scholefield
email: matthew.d.scholefield@gmail.com
description: >
  Matthew D. Scholefield is a software developer with a focus
  in machine learning. Other passions include graphic design
  and music composition.
url: "http://matthewscholefield.github.io"
github_username:  matthewscholefield

include:
  - .nojekyll

exclude:
  - "Rakefile"
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"

# Build settings
markdown: kramdown
